# Generated by Django 3.2.19 on 2023-06-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_profile_nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('side_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('facebook_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='facebook_link')),
                ('linkedin_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='linkedin_link')),
                ('github_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='github_link')),
                ('researchgate_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='researchgate_link')),
                ('google_sch_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='google_sch_link')),
                ('my_website_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_website_link')),
                ('my_kaggle_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_kaggle_link')),
                ('my_email', models.EmailField(blank=True, db_index=True, max_length=128, verbose_name='my_email')),
                ('my_twitter', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_twitter_link')),
                ('my_ig', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_ig_link')),
                ('my_stack_overflow', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_stack_overflow')),
                ('my_medium_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_medium_link')),
                ('my_facebook', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_facebook')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
