# Generated by Django 3.2.19 on 2023-06-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_my_profile_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(blank=True, max_length=100, null=True)),
                ('con_email', models.EmailField(blank=True, db_index=True, max_length=128, verbose_name='my_email')),
                ('con_message', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=300, null=True)),
                ('blog_short_dis', models.TextField(blank=True, max_length=600, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog_readtime', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_publish_time', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_medium_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='blog_medium_link')),
                ('Featured', models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='My_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(blank=True, max_length=300, null=True)),
                ('portfolio_short_dis', models.TextField(blank=True, max_length=600, null=True)),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('portfolio_readtime', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_publish_time', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_medium_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='portfolio_medium_link')),
                ('portfolio_git_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='portfolio_git_link')),
                ('portfolio_live_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='portfolio_live_link')),
                ('Featured', models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='My_researche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(blank=True, max_length=300, null=True)),
                ('research_short_dis', models.TextField(blank=True, max_length=600, null=True)),
                ('research_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('research_published_by', models.CharField(blank=True, max_length=300, null=True)),
                ('research_publish_time', models.CharField(blank=True, max_length=100, null=True)),
                ('research_readmore_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='research_readmore_link')),
                ('research_publication_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='research_publication_link')),
                ('Featured', models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='testiomonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_details', models.TextField(blank=True, max_length=800, null=True)),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('test_job_status', models.CharField(blank=True, max_length=200, null=True)),
                ('test_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
